### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [adelacvg/ttts#1]
Please add a license. Please keep in mind that MPL (Coqui) may have restrictions on the license. Thank you!

**Comment by adelacvg** [comment]
Thank you, I have already added the license.

**Comment by fakerybakery** [comment]
Thanks!

**Comment by fakerybakery** [comment]
Hi, I saw that you released V4 - very cool! from the readme file it seems that it is no longer based on XTTS. Is there any chance of switching it to a more permissive license? Thanks!
