### ISSUE TITLE
Training diffusion error

### ISSUE THREAD

**Issue by XierHacker** [adelacvg/ttts#10]
Hello, I went to the [diffusion step] based on your code, and then the following errors appeared.

`omegaconf.errors.ConfigAttributeError: Missing key timm_model_name , full_key: clip.vision_cfg.timm_model_name`

I think this parameter（timm_model_name）is not written in the diffusion configuration, so I would like to ask what configuration your pretrained model is based on.

**Comment by adelacvg** [comment]
You can try the following command to solve this. 
`pip install omegaconf==2.0.6`

**Comment by XierHacker** [comment]
> You can try the following command to solve this. `pip install omegaconf==2.0.6`

Thank you very much, the problem has been solved. 
But in the end my results were not very good. Below is my training curve. Are there any errors in it?


GPT：
<img width="825" alt="image" src="https://github.com/adelacvg/ttts/assets/15364826/04a57fc0-bb21-46e9-8c1d-7dc416943337">

diffusion：
<img width="743" alt="image" src="https://github.com/adelacvg/ttts/assets/15364826/13daaead-2913-4f1d-ab23-28cd285dece5">

**Comment by adelacvg** [comment]
How many hours of data did you use for training? Additionally, your diffusion model has not undergone sufficient training; it requires at least 100k steps of training to achieve good results. Moreover, it is currently recommended to train models on the v2 branch. The v2 version of GPT incorporates longer speaker conditions, resulting in lower loss.

**Comment by XierHacker** [comment]
> How many hours of data did you use for training? Additionally, your diffusion model has not undergone sufficient training; it requires at least 100k steps of training to achieve good results. Moreover, it is currently recommended to train models on the v2 branch. The v2 version of GPT incorporates longer speaker conditions, resulting in lower loss.

Thank you for your reply. I have used a total of 3000 hours of voice data, about 2 million samples. For the diffusion model, its loss curve drops so quickly, Is it correct?

**Comment by adelacvg** [comment]
Indeed, the loss from diffusion drops fast and has no value. It's crucial to observe the gradient dropping below 0.02 for a good model.
