### ISSUE TITLE
Unstable pronunciation

### ISSUE THREAD

**Issue by XierHacker** [adelacvg/ttts#11]
Hello, I followed all your training steps. But the generated audio has serious pronunciation problems. It feels like there are some problems with the GPT part. But debugging doesn't show the problem. 
May I ask if you have any experience in handling this situation?

text: "中部地区如江汉平原，当前冬小麦普遍到了拔节期，南方则进入孕穗期，这时候小麦幼穗对外界环境更加敏感，长时间降温甚至降雪，可能会形成局部冻害。"
[results.zip](https://github.com/adelacvg/ttts/files/14341848/results.zip)

我使用了main中的训练代码，但是并没有限制到最少4s，请问一下，代码中限制音频最少4s是基于什么考虑呢？

**Comment by adelacvg** [comment]
你好，4s设置的其实并不科学，tortoise中最短为2s最长20s，我在v2分支中改为了最短1s最长20s。在实验中我发现了一个现象“没有训练过的时长模型会生成不了”，比如截断到4s的模型会生成不了4s以下的音频，以上的生成都正常，截断到20s的模型无法稳定生成30s或40s的音频。

这个问题主要是因为使用了绝对位置编码，但事实上rope或interleave等方法也无法保证与截断区间内部相同程度的稳定生成。result.zip中音频在后半段无法正常生成，我认为可能是数据集中的长音频数据量较少导致的，保持训练和推理的一致性是训练好的gpt模型要遵循的一个准则。

现有的开源数据大多是5秒以内的较短的音频，这其实并不适合用来训练大模型，高质量的短音频更适合训练声码器与扩散模型部分。

**Comment by XierHacker** [comment]
非常感谢你的回复，目前我这边短音频生成也依然不稳定；同时也存在很多的例子前半部分不好，后面变好的情况，有点难以定位问题。

**Comment by adelacvg** [comment]
gpt模型训练不好一般是数据的问题，可以检查数据清洗部分是否处理得当，或是尝试在更大的数据量上进行更长时间的训练。

**Comment by XierHacker** [comment]
> gpt模型训练不好一般是数据的问题，可以检查数据清洗部分是否处理得当，或是尝试在更大的数据量上进行更长时间的训练。

好的，非常感谢您的回复，
