### ISSUE TITLE
train hifigan failed

### ISSUE THREAD

**Issue by wflrz123** [adelacvg/ttts#17]
I am currently retraining a 16k HiFi-GAN, but using latent as the input, the loss is difficult to converge. Although human voice can be heard, there is a presence of electronic sound. What could be the reason for this? Looking forward to your reply, thank you.

**Comment by howitry** [comment]
> I am currently retraining a 16k HiFi-GAN, but using latent as the input, the loss is difficult to converge. Although human voice can be heard, there is a presence of electronic sound. What could be the reason for this? Looking forward to your reply, thank you.

Hello, I also encountered this problem when training 24k hifigan. Do you have a solution now?
