### ISSUE TITLE
Will this be faster than Tortoise?

### ISSUE THREAD

**Issue by fakerybakery** [adelacvg/ttts#2]

**Comment by adelacvg** [comment]
Yes, I hope this model can run as fast as XTTS.

**Comment by fakerybakery** [comment]
Amazing! What about the improvements from XTTSv2?

**Comment by adelacvg** [comment]
The zero-shot capability will be much stronger than XTTSv2.

**Comment by fakerybakery** [comment]
Nice, sounds incredible! I hope English support comes soon!

**Comment by Liujingxiu23** [comment]
> The zero-shot capability will be much stronger than XTTSv2.

why the capability is much stronger?  because of the diffusion part?

**Comment by adelacvg** [comment]
> > The zero-shot capability will be much stronger than XTTSv2.
> 
> why the capability is much stronger? because of the diffusion part?

I add perceiver to gpt2 like xtts_v2. Add referencenet and mrte to diffusion. The structures seem to work based on lower loss and lower gradient norms, but they still need to be validated on a large amount of data.
