### ISSUE TITLE
How is the performance of this code?

### ISSUE THREAD

**Issue by zzw922cn** [adelacvg/ttts#3]
Hi, thanks for your nice work on TTS. I want to know, did you have train this? How is the performance of TTS?

**Comment by adelacvg** [comment]
The core model has been validated on small-scale data. I am currently collecting data and training the model, and the inference speed is expected to be on par with Xtts.

**Comment by zzw922cn** [comment]
thanks! do you have plan to suport CVLP ranking module?

**Comment by Liujingxiu23** [comment]
@adelacvg your work is great since tortose is complicated for training. I wonder how is the performance now?

**Comment by adelacvg** [comment]
> @adelacvg your work is great since tortose is complicated for training. I wonder how is the performance now?

You can try the colab demo of v1 branch. It is comparable with tortoise results. Zero-shot is still not very usable; I’m working on it.

**Comment by Liujingxiu23** [comment]
Thank you for your reply! I'll follow your work as long as you update your work!
