### ISSUE TITLE
How long train a new model

### ISSUE THREAD

**Issue by HobisPL** [adelacvg/ttts#8]
How long does it take to train a model from scratch, and how much dataset is needed?

**Comment by adelacvg** [comment]
5000 hours is an appropriate duration for dataset, and it will take approximately one week to complete the training for all models.

**Comment by yuan1615** [comment]
What kind of computing power support is needed for a week?

**Comment by adelacvg** [comment]
I trained all the models on four GTX 3090 GPUs.

**Comment by yuan1615** [comment]
Thank you for your reply.
